version: '3'
services:
  # MySQL
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    # データ永続化する場合はmysql_dataディレクトリを作って保存
    # volumes:
    #   - ./mysql_data:/var/lib/mysql

  # Rails
  web:
    build:
      context: ./
      dockerfile: ./dockerfile/rails/Dockerfile
    volumes:
      - ./src:/myapp
    ports:
      - "5000:3000"
      - "3035:3035"
    links:
      - db
    tty: true
    stdin_open: true
